// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E_Voucher.Entities.Database.EVoucherSystem.DbModel
{
    public partial class TblBuyType
    {
        public int Id { get; set; }
        public string BuyType { get; set; }
        public string Description { get; set; }
        public short? MaxLimit { get; set; }
        public short Status { get; set; }
    }
}