// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E_Voucher.Entities.Database.EVoucherSystem.DbModel
{
    public partial class TblGeneratedEvoucher
    {
        public string PromoCode { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string VoucherNo { get; set; }
        public string QrImagePath { get; set; }
        public string VoucherImagePath { get; set; }
        public string OwnerName { get; set; }
        public string OwnerPhone { get; set; }
        public decimal VoncherAmount { get; set; }
        public DateTime ExpiryDate { get; set; }
        public short Status { get; set; }
        public int Id { get; set; }
    }
}