// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E_Voucher.Entities.Database.EVoucherSystem.DbModel
{
    public partial class TblPurchaseHistory
    {
        public int PurchaseHistoryId { get; set; }
        public string PromoCode { get; set; }
        public string VoucherNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public DateTime PurchaseDate { get; set; }
        public short Status { get; set; }
    }
}