// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E_Voucher.Entities.Database.EVoucherSystem.DbModel
{
    public partial class TblPaymentMethod
    {
        public string PaymentMethod { get; set; }
        public string Description { get; set; }
        public bool? IsDiscount { get; set; }
        public int DiscountPercentage { get; set; }
        public short Status { get; set; }
        public int Id { get; set; }
    }
}