// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E_Voucher.Entities
{
    public partial class TblEvoucher
    {
        public string VoucherNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string ImagePath { get; set; }
        public string BuyType { get; set; }
        public decimal VoucherAmount { get; set; }
        public string PaymentMethod { get; set; }
        public decimal SellingPrice { get; set; }
        public short? SellingDiscount { get; set; }
        public int MaxLimit { get; set; }
        public int GiftPerUserLimit { get; set; }
        public short Status { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? LastUpdatedBy { get; set; }
        public DateTime? LastUpdatedOn { get; set; }
        public int Id { get; set; }
    }
}