// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace E_Voucher.Entities
{
    public partial class TblUserPassword
    {
        public int UserId { get; set; }
        public string Password1 { get; set; }
        public string Password2 { get; set; }
        public string Password3 { get; set; }
        public string ActivePassword { get; set; }
        public short Status { get; set; }
        public int Id { get; set; }
    }
}